### PR TITLE
Use latest cibuildwheel version 2.3.0

### PR DESCRIPTION
**Pull request by cbrnr**
Let's see how this affects the number of wheels that are built.

### CODE REVIEW

**Comment by cbrnr** [comment]
Numba for Python 3.10 should be available very soon hopefully (https://github.com/numba/numba/issues/7562), so let's restart the tests once this is the case.

**Comment by hofaflo** [comment]
Nice idea!

Skipping 3.10 for now by extending `CIBW_SKIP: pp*` to `CIBW_SKIP: pp* cp310-*` should allow to test this right now.

Side note: using this newer cibuildwheel version would allow configuration via `pyproject.toml`, so we could avoid setting the same environment variables in both workflows.

**Comment by cbrnr** [comment]
OK! Can you push your suggested changes?

**Comment by hofaflo** [comment]
cibuildwheel v2.2.0 introduced support for building musllinux wheels, which [doesn't work in our case](https://github.com/cbrnr/sleepecg/runs/4499217025?check_suite_focus=true), so I guess we'll skip them?

Yep, looks like your goal was achieved, there's now only one manylinux wheel (which is tagged for multiple manylinux versions) per python version 🥳

**Comment by cbrnr** [comment]
Yes, I think we can safely ignore musl.

**Comment by hofaflo** [comment]
Perfect, thanks @cbrnr!

**Pull request merged**
