### PR TITLE
Add Python 3.11 support

### PR DESCRIPTION
**Pull request by cbrnr**
I *think* cibuildwheel should already build 3.11 wheels, let's see...

### CODE REVIEW

**Comment by cbrnr** [comment]
We have to wait for Numba to support 3.11 (https://github.com/numba/numba/issues/8304).

**Comment by hofaflo** [comment]
Tensorflow also doesn't support 3.11 yet, do you think we should add a note about that somewhere, e.g. put a disclaimer in the (yet to write) changelog entry?

Also, this worked locally, I'll try to find out why the CI still fails :thinking:

**Comment by hofaflo** [comment]
Fixed, missed one of the `numba`s :sweat_smile:

**Comment by cbrnr** [comment]
This is a very nice solution! Thanks @hofaflo!

**Pull request merged**
