### PR TITLE
Improve docstring for heartbeats function

### PR DESCRIPTION
**Pull request by raphaelvallat**
Hi @cbrnr and @hofaflo,

I have just added some examples in the docstring of the functions. I think this will be useful. Feel free to edit the text.

Thanks,
Raphael

### CODE REVIEW

**Comment by cbrnr** [comment]
Thanks @raphaelvallat, these examples will be very helpful indeed. However, since they are already pretty long, what do you think about including them in the documentation instead of in the docstrings? We could create an "Example" section e.g. right after "Usage" on https://sleepecg.readthedocs.io/en/stable/heartbeat_detection.html?

If you think examples would be useful in docstrings, I'd prefer shorter examples (that we could maybe also doctest automatically).

**Comment by raphaelvallat** [comment]
Hi @cbrnr,

I tend to only read the API and not really the documentation, so for me having at least a minimal example in the docstring is definitely useful. But we can shorten what I have done, and include the full example in the heartbeat_detection.md file.

Also, I do think that the doctest would work even with the current (long) examples.

**Comment by raphaelvallat** [comment]
@cbrnr done. Feel free to edit!

**Comment by cbrnr** [comment]
Thanks @raphaelvallat!

**Pull request merged**
